### ISSUE TITLE
Missing compile flag

### ISSUE THREAD

**Issue by matthewvroman** [treasure-data/td-unity-sdk-package#3]
**Problem:**
The TreasureData Unity plugin crashes on iOS unless the '-fno-objc-arc' compile flag is added to NativePlugin.mm

**Solution:**
Either documentation should clearly mention inclusion of the compile flag, or the compile flag should not be required

**Reproduction Steps:**
1. Checkout this git repository from hash ced60f5c6f466077a463c1e2e95fbd3f534e8ff9
2. Open the example project in Unity
3. Import TD-Unity-SDK-0.1.7.unitypackage into project
4. Relink the missing Monobehaviors in the Main scene so each GUIText game object has a TreasureDataExampleScript component
4. Enter valid API key, database name, and table name into TreasureDataExampleScript
5. Build to Xcode 
6. In Build Phases, add libz.tbd under Link Binary with Libraries
7. Compile and run app on device
8. Notice the app crashes when tapping 'Add Event'
9. In Build Phases under Compile Sources, add the '-fno-objc-arc' compile flag to NativePlugin.mm
10. Rebuild and run the app
11. Notice the app no longer crashes when tapping 'Add Event'

**Additional Details:**
Unity Version 5.5.1p3
Xcode Version 8.2.1 (8C1002)
iOS Version 10.0.1 (14A403)

**Comment by komamitsu** [comment]
@matthewvroman Thanks for reporting! I'll look into it.

**Comment by komamitsu** [comment]
@matthewvroman Can I ask you to paste the stack trace of this crash? Thanks

**Comment by matthewvroman** [comment]
@komamitsu I've attached the stack trace here: [td-stacktrace.txt](https://github.com/treasure-data/td-unity-sdk-package/files/789349/td-stacktrace.txt)

It also might help to let you know that when I enabled Zombie Objects on the build I see this error:
`2017-02-20 23:21:09.176549 TreasureDataTest[5022:2796569] *** -[TreasureData retain]: message sent to deallocated instance 0x1684ddd0`

Let me know if you need any additional details

**Comment by komamitsu** [comment]
@matthewvroman Thanks. And this issue is reproduced on my side as well with the same stack trace.
The SDK worked well as is with Xcode 7. So I'm wondering the changes between Xcode 7 and 8 may caused something wrong. Let me investigate it more.

**Comment by komamitsu** [comment]
This error occurs when calling other API (e.g. `EnableAutoAppendUniqId()`) as well.

**Comment by komamitsu** [comment]
https://forum.unity3d.com/threads/unity-ios-64-bit-support.287172/

> plugins that are targeting Unity 5.0 should keep in mind that Unity 5.0 Xcode project has ARC enabled by default, so plugin code available as ObjC files should be ARC compatible, or plugin integration script should ensure that these files have additional compile option -fno-objc-arc set when added to Xcode project. Also precompiled plugins that are using standard C++ libraries should be compiled with libc++ (LLVM C++ standard library with C++11 support) option in Xcode.

@matthewvroman As you suggested, I'll update the document of this SDK to mention additional compile option `-fno-objc-arc` to NativePlugin.mm later.

**Comment by matthewvroman** [comment]
@komamitsu Great! Thanks for looking into all this!

**Comment by komamitsu** [comment]
@matthewvroman Added the explanation https://github.com/treasure-data/td-unity-sdk-package#in-case-of-ios-application
Thanks!
